options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t node-app -f dockerfile .
      docker images
      docker tag node-app asia-south1-docker.pkg.dev/niveus-gcp-training-1/simi-repo/node-app:a1
      docker push asia-south1-docker.pkg.dev/niveus-gcp-training-1/simi-repo/node-app:a1
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth list
      gcloud config list
